services:
  - type: web
    name: cryptopulse-frontend
    env: node
    region: oregon
    plan: starter
    autoDeploy: true
    rootDir: Cryptopulse--main/frontend
    # FIXED: Proper pnpm installation with peer dependency resolution
    # Single line command for better Render compatibility
    buildCommand: corepack enable && rm -rf node_modules .pnpm-store && pnpm install --no-frozen-lockfile --shamefully-hoist=true --strict-peer-dependencies=false && pnpm build
    startCommand: node server.cjs
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: VITE_API_BASE_URL
        value: https://cryptopulse-backend-j4ne.onrender.com
      - key: VITE_APP_NAME
        value: CryptoPulse
      - key: VITE_APP_VERSION
        value: "2.0.0"
      # IMPORTANT: Set a secure 32+ char string in Render UI or via blueprint overrides
      - key: VITE_ENCRYPTION_KEY
        generateValue: true
        previewValue: "CHANGE_ME_TO_A_SECURE_RANDOM_32+_CHAR_STRING"
      # Build optimization
      - key: VITE_ENABLE_SOURCEMAPS
        value: "false"
      - key: VITE_BUILD_TARGET
        value: "production"
      - key: VITE_MINIFY
        value: "true"
      # API configuration
      - key: VITE_API_TIMEOUT
        value: "30000"
      - key: VITE_API_RETRY_ATTEMPTS
        value: "3"
      # Performance
      - key: VITE_ENABLE_COMPRESSION
        value: "true"
      - key: VITE_CHUNK_SIZE_WARNING_LIMIT
        value: "1000"

