services:
  - type: web
    name: cryptopulse-frontend
    env: node
    region: oregon
    plan: starter
    autoDeploy: true
    rootDir: Cryptopulse--main/frontend
    buildCommand: corepack enable && pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=460"
      - key: VITE_API_BASE_URL
        value: https://cryptopulse-backend-j4ne.onrender.com
      - key: VITE_APP_NAME
        value: CryptoPulse
      - key: VITE_APP_VERSION
        value: "2.0.0"
      # IMPORTANT: Set a secure 32+ char string in Render UI or via blueprint overrides
      - key: VITE_ENCRYPTION_KEY
        generateValue: true
        previewValue: "CHANGE_ME_TO_A_SECURE_RANDOM_32+_CHAR_STRING"
      # Optional, recommended
      - key: VITE_ENABLE_SOURCEMAPS
        value: "false"
      - key: VITE_API_TIMEOUT
        value: "30000"
      - key: VITE_API_RETRY_ATTEMPTS
        value: "3"

