# =============================================================================
# CryptoPulse Prometheus Configuration - 100% Production Ready
# =============================================================================
# World-Class Production Monitoring with Prometheus

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cryptopulse-production'
    environment: 'production'

# =========================================================================
# Rule Files
# =========================================================================
rule_files:
  - "rules/*.yml"

# =========================================================================
# Alerting Configuration
# =========================================================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# =========================================================================
# Scrape Configurations
# =========================================================================
scrape_configs:
  # =========================================================================
  # Prometheus Self-Monitoring
  # =========================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # =========================================================================
  # Backend API Services
  # =========================================================================
  - job_name: 'cryptopulse-backend'
    static_configs:
      - targets: ['backend:1337', 'backend-2:1337']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # =========================================================================
  # Frontend Services
  # =========================================================================
  - job_name: 'cryptopulse-frontend'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # =========================================================================
  # Cloud Services
  # =========================================================================
  - job_name: 'cryptopulse-cloud'
    static_configs:
      - targets: ['cloud:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # =========================================================================
  # Nginx Load Balancer
  # =========================================================================
  - job_name: 'cryptopulse-nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 10s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # =========================================================================
  # PostgreSQL Database
  # =========================================================================
  - job_name: 'cryptopulse-postgres'
    static_configs:
      - targets: ['postgres:5432', 'postgres-replica:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # =========================================================================
  # Redis Cache
  # =========================================================================
  - job_name: 'cryptopulse-redis'
    static_configs:
      - targets: ['redis:6379', 'redis-replica:6379']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # =========================================================================
  # MongoDB
  # =========================================================================
  - job_name: 'cryptopulse-mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # =========================================================================
  # Node Exporter (System Metrics)
  # =========================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # =========================================================================
  # cAdvisor (Container Metrics)
  # =========================================================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # =========================================================================
  # Docker Daemon
  # =========================================================================
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['docker-daemon:9323']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# =========================================================================
# Storage Configuration
# =========================================================================
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# =========================================================================
# Remote Write Configuration (Optional)
# =========================================================================
# remote_write:
#   - url: "https://your-remote-storage.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
